# Generated by Django 3.1.14 on 2024-04-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0094_auto_20190903_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_model_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_model',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
